services:
  kpi-generator:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config:/app/config
      - ./output:/app/output
      - ./static:/app/static
      # 認証キーをマウントしてコンテナ内で使用できるようにする
      - ./keys:/app/keys
    environment:
      - NODE_ENV=production
      - GOOGLE_SERVICE_ACCOUNT_KEY_PATH=/app/keys/service-account-key.json
      - KPI_TREE_SPREADSHEET_ID=1kCEQwecJyjJztEaTCLfJwkDfi1rsxcGEhBdLZb6F2Z0
    # コマンドライン引数を渡すことができます（例：docker-compose run kpi-generator sales）
    # デフォルトはconfig.yaml