services:
  kpi-generator:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config:/app/config
      - ./output:/app/output
      - ./static:/app/static
      # srcディレクトリをマウント（開発中の変更をすぐに反映するため）
      - ./src:/app/src
      # スクリプトをマウント
      - ./generate_historical_report.py:/app/generate_historical_report.py
      - ./generate_historical_report.sh:/app/generate_historical_report.sh
      - ./generate_historical_report_docker.py:/app/generate_historical_report_docker.py
      - ./test_python_script.py:/app/test_python_script.py
      # 認証キーをマウントしてコンテナ内で使用できるようにする
      - ./keys:/app/keys
    environment:
      - NODE_ENV=production
      - GOOGLE_SERVICE_ACCOUNT_KEY_PATH=/app/keys/service-account-key.json
      # 特定のスプレッドシートIDを環境変数として指定する場合（YAMLファイルの設定が優先されます）
      # - KPI_TREE_SPREADSHEET_ID=your_spreadsheet_id_here
    # コマンドライン引数を渡すことができます（例：docker-compose run kpi-generator sales）
    # デフォルトはconfig.yaml

  update-html:
    build:
      context: .
      dockerfile: Dockerfile.update-html
    volumes:
      - ./output:/app/output
      - ./static:/app/static
      - ./sql:/app/sql
      - ./keys:/app/keys
      - ./update_html.py:/app/update_html.py
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/keys/service-account-key.json
    # コマンドライン引数を渡すことができます（例：docker-compose run --rm update-html --target_date 2025-05-22）