title: "Game KPIs"
theme: "blue"

# 公開時のURL設定（GCSなどでホスティングする場合に使用）
public_url: "https://storage.googleapis.com/your-bucket/game.html"

root:
  text: "Revenue (JPY)"
  value: 300,000,000
  url: "https://example.com/revenue"
  children:
    - text: "Product A"
      value: 150,000,000
      children:
        - text: "Active Users"
          value: 100,000
          operator: "*"
        - text: "ARPU"
          value: 1,500
          operator: "*"
          children:
            - text: "ARPPU"
              value: 10,000
              operator: "*"
            - text: "課金率"
              value: 15%
              operator: "*"
      operator: "+"
    - text: "Product B"
      value: 150,000,000
      children:
        - text: "Active Users"
          value: 100,000
          operator: "*"
        - text: "ARPU"
          value: 1,500
          operator: "*"
          children:
            - text: "ARPPU"
              value: 10,000
              operator: "*"
            - text: "課金率"
              value: 15%
              operator: "*"
      operator: "+"