title: "Game KPIs"
theme: "blue"
# 公開時のURL設定（GCSなどでホスティングする場合に使用）
public_url: "https://storage.googleapis.com/kpi-tree-data/game.html"

# グローバルスプレッドシート設定 - すべてのノードで共有
spreadsheet:
  id: "1kCEQwecJyjJztEaTCLfJwkDfi1rsxcGEhBdLZb6F2Z0"

# ヘッダー表示のカスタム情報
header_info:
  label: "DAU"  # ヘッダーに表示するラベル
  # スプレッドシート参照文字列をそのまま使用
  value: "=sample!C8"  # DAUの値を取得

root:
  text: "売上"
  text_en: "Revenue (JPY)"
  # 日次・月次データを別々に設定（簡易形式で統一）
  value_daily: "=sample!B1"
  value_monthly: "=sample!C1"  # 月次データは異なるセルを参照
  diff_daily: "=sample!E1"
  diff_monthly: "=sample!F1"
  url: "https://example.com/revenue"
  children:
    - text: "Product A"
      operator: "+"
      # 簡易形式で日次・月次を指定
      value_daily: "=sample!C2"
      value_monthly: "=sample!D2"
      diff_daily: "=sample!E2"
      diff_monthly: "=sample!F2"
      children:
        - text: "Active Users"
          # 両方とも簡易形式に統一
          value_daily: "=sample!C3"
          value_monthly: "=sample!D3"
          diff_daily: "=sample!E3"
          diff_monthly: "=sample!F3"
          operator: "*"
        - text: "ARPU"
          # 最も簡易な形式で日次・月次データを指定
          value_daily: "=sample!C4"
          value_monthly: "=sample!D4"
          diff_daily: "=sample!E4"
          diff_monthly: "=sample!F4"
          operator: "*"
          children:
            - text: "ARPPU"
              value_daily: "=sample!C5"
              value_monthly: "=sample!D5"
              diff_daily: "=sample!E5"
              diff_monthly: "=sample!F5"
              operator: "*"
            - text: "課金率"
              value_daily: "=sample!C6"
              value_monthly: "=sample!D6"
              diff_daily: "=sample!E6"
              diff_monthly: "=sample!F6"
              operator: "*"
    - text: "Product B"
      operator: "+"
      # 簡易形式で日次・月次を指定
      value_daily: "=sample!C7"
      value_monthly: "=sample!D7"
      diff_daily: "=sample!E7"
      diff_monthly: "=sample!F7"
      children:
        - text: "Daily Active Users"
          value_daily: "=sample!C8"
          value_monthly: "=sample!D8"
          diff_daily: "=sample!E8"
          diff_monthly: "=sample!F8"
          operator: "*" 
        - text: "Conversion Rate"
          value_daily: "=sample!C9"
          value_monthly: "=sample!D9"
          diff_daily: "=sample!E9"
          diff_monthly: "=sample!F9"
          operator: "*"
          children:
            - text: "Retention"
              value_daily: "=sample!C10"
              value_monthly: "=sample!D10"
              diff_daily: "=sample!E10"
              diff_monthly: "=sample!F10"
              operator: "+"
            - text: "課金率（長い文字列の表示テスト。あああああああああああああああああああああああああ）"
              value_daily: "=sample!C11"
              value_monthly: "=sample!D11"
              diff_daily: "=sample!E11"
              diff_monthly: "=sample!F11"
              operator: "+"